linters-settings:
  errcheck:
    exclude-functions:
      - (github.com/jackc/pgx/v5.Tx).Rollback
  staticcheck:
    checks: ["all"]
  stylecheck:
    checks: ["all"]
  funlen:
    lines: 200
  cyclop:
    max-complexity: 30
  varnamelen:
    max-distance: 15
    ignore-names:
      - id # generael identifier
      - err # error values
      - db # database connections
      - tx # database transactions
      - w # io.Writers
      - r # io.Readers or http.Request
      - ok # common bool
      - rw # read-write database
      - ro # read-only database
      - ds # field path
      - g # code generator group
linters:
  enable-all: true
  disable:
    - dupl # false positive galore
    - exhaustruct # CDK has large structs we use partially
    - gochecknoinits # frameworks and magefile use init responsibly
    - gci # no way to automate this in the vscode so default ordering is good enough
    - ireturn # our oapi implementations return interfaces all the time
    - depguard # too agressive
    - tagliatelle # we have lots of aws tags that don't follow the standards
    - nonamedreturns # makes some functions very unreadable
    - wsl # too strict
    - gochecknoglobals # too strict
    - gomoddirectives # can't get this to shutup
    - goconst # text identifiers makes it more readable
    - funlen # trust our own judgement
    - err113 # too much effort
    - perfsprint #microoptimization
    - gomnd
    - canonicalheader
    - execinquery
    - unparam # don't be too smart
    - dupword # gets in the way often when we're commenting out stuff
    - containedctx # actually common for actors/workers that have a context for the lifetime
    - paralleltest # too anoying
    - mnd # too annoying

issues:
  include:
    - EXC0015 # warn for lack of package comment
    - EXC0013 # warn for lack of package comment
    - EXC0012 # EXC0012 revive: Annoying issue about not having a comment. The rare codebase has such comments
    - EXC0014 # EXC0014 revive: Annoying issue about not having a comment. The rare codebase has such comments
  exclude-dirs:
    - infra/builds
    - node_modules
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
        - forcetypeassert
        - gochecknoglobals
        - lll
        - err113
        - revive
        - perfsprint
        - wrapcheck
        - nlreturn
        - varnamelen
        - errcheck
        - nilnil
    - path: infra
      linters:
        - mnd
        - interfacebloat
        - goconst
    - path: migrations
      linters:
        - unused
        - unparam
        - lll
    - path: lambda
      linters:
        - nilnil
    - path: magefiles
      linters:
        - mnd
        - err113
        - goconst
        - wrapcheck
    - path: e2e
      linters:
        - mnd
        - err113
        - goconst
        - wrapcheck
        - protogetter
